# Generated by Django 5.1.2 on 2024-11-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0002_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
