# Generated by Django 5.1.2 on 2024-11-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0005_remove_reservation_status_alter_reservation_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('acceptée', 'Acceptée'), ('refusée', 'Refusée')], default='en_attente', max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='number',
            field=models.IntegerField(),
        ),
    ]
