# Generated by Django 5.1.3 on 2024-11-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0007_alter_reservation_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_place', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='number',
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='tel',
            field=models.CharField(max_length=10),
        ),
    ]
