# Generated by Django 5.1.3 on 2024-11-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0009_alter_reservation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
