# Generated by Django 5.1.2 on 2024-11-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0009_alter_reservation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(default='Table inconnue', max_length=100),
        ),
    ]
